spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/
  datasource:
    username: root
    password: Adilakshmi@1
    url: jdbc:mysql://localhost:3306/sbms

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
 port: 8081

Authentication_Service :
    messages :
      userReg : User Registered 
      authFailed : Authentication failed
      userAdded : User Added
      userUpdated : User Updated
      userDeleted : User deleted
      userRecords : User Records 
      userRecord : User Record
