spring:  
  datasource:
    url: jdbc:mysql://localhost:3306/sbms  
    username: root
    password: Adilakshmi@1
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  
  boot:
    admin:
      client:
        url: http://localhost:1111/
        


management:
  endpoints:
    web:
      exposure:
        include: "*" 
        
server:
  port: 8086          
        
payment-service :
 messages :
  success : paymentSuccessfull
  failed : paymentFailed
  
              
    
