spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/
  datasource:
    username: root
    password: Adilakshmi@1
    url: jdbc:mysql://localhost:3306/sbms

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8082
          
product-service :
  messages :
    productAdded : Product Added
    productRetrieved : Product Retrieved
    productsRetrieved : Products Retrieved
    productUpdated : Product Updated 
    productDeleted : Product Deleted
    categoryAdded : Category Added
    categoryRetrieved : Category Retrieved
    categoriesRetrieved : Categories Retrieved
    categoryUpdated : Category Updated 
    categoryDeleted : Category Deleted

        
        

        
