spring:      
  datasource:
    url: jdbc:mysql://localhost:3306/sbms  
    username: root
    password: Adilakshmi@1
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  boot:
    admin:
      client:
        url: http://localhost:1111/
        
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
reports-service: 
 messages: 
  reportsRetrieved: Reports Retrieved Successfully
  reportsRetrievedByDate: Reports Retrieved By Date Successfully
  reportsRetrievedByDateErr: failed To Retrieve The Reports By Date
  reportsRetrievedByStatus: Reports Retrieved By Id Successfully
  reportsRetrievedByStatusErr: failed To Retrieve The Reports By Id 
  reportsRetrievedErr: failed To Retrieve The Reports
  
server:
  port: 8085      
